version: '3.8'

services:
  web:
    container_name: web
    build: 
      context: ./procesamiento_imagenes
      dockerfile: Dockerfile  # El Dockerfile de Python
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    container_name: db
    build:
      context: ./repositorio_bd
      dockerfile: Dockerfile  # El Dockerfile de MySQL
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: historico_archivos
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    
