from config_vars import ConfigVars
import os

class Config:

    os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = 'servicio_google_ocr.json'

    SQLALCHEMY_DATABASE_URI = ConfigVars.DATABASE_URL
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    GOOGLE_APPLICATION_CREDENTIALS = ConfigVars.GOOGLE_APPLICATION_CREDENTIALS
    DOCUMENT_AI_ENDPOINT = ConfigVars.DOCUMENT_AI_ENDPOINT
    DOCUMENT_AI_LOCATION = ConfigVars.DOCUMENT_AI_LOCATION
    DOCUMENT_AI_PROJECT_ID = ConfigVars.DOCUMENT_AI_PROJECT_ID
    DOCUMENT_AI_PROCESSOR_ID = ConfigVars.DOCUMENT_AI_PROCESSOR_ID
    GENERATIVE_AI_API_KEY = ConfigVars.GENERATIVE_AI_API_KEY
    FILES_DIRECTORY = ConfigVars.FILES_DIRECTORY

